-- Базовая настройка
require("core.plugins")
require("core.color")
require("core.config")
require("core.autocmds")
require("core.utils")
require("core.ru_mappings")
require("core.mappings")

require("plugins.dashboard")
require("plugins.neotree")
require("plugins.gitsigns")
require("plugins.mason")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.dap")
require("plugins.treesitter")
require("plugins.bufferline")
require("plugins.lualine")
require("plugins.autopairs")
require("plugins.toggleterm")
require("plugins.colortils")
require("plugins.colorizer")
require("plugins.comment")
require("plugins.whichkey")
